$ExorVMInstall = <<SCRIPT

set -e

# Install required packages and setup source repositories
apt-get update
apt-get install -y dictionaries-common
apt-get install -y xfce4 xfce4-terminal xfce4-xkb-plugin dos2unix ifmetric gedit
apt-get install -y git python diffstat texinfo gawk chrpath wget nano firefox humanity-icon-theme
apt-get install -y --force-yes build-essential qtcreator qtdeclarative5-qtquick2-plugin libqt4-dev
apt-get install -y xinit xserver-xorg-input-evdev bc g++-multilib libgl1-mesa-dev
apt-get install -y avahi-daemon avahi-utils

# Remove some wait on network configuration
sed -i'' 's:\tsleep.*:sleep 2:' /etc/init/failsafe.conf

# Remove cloud-init, speeds up the boot
apt-get purge -y cloud-init
rm -rf /etc/init/cloud*

exit 0

SCRIPT


Vagrant.configure(2) do |config|
  
  config.vm.box = "ubuntu/trusty64"
  
  config.vm.hostname = "ExorDev-VM"
  config.vm.network "public_network"
  
  config.vm.provision "shell", inline: $ExorVMInstall
  
  config.vm.provider "virtualbox" do |v|
    v.name = "ExorDev-VM-stage1"
    v.memory = 2048
    v.cpus = 2
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.customize ["modifyvm", :id, "--hwvirtex", "on"]
	v.customize ["modifyvm", :id, "--usb", "on"]
    v.gui = false
  end
end